### PR TITLE
Milestone 1 - Chloe Lo

### PR DESCRIPTION
**Pull request by sylochloe**
# Milestone: {Milestone #} 1
# Developer: {Full Name} Chloe Lo

### Pull Request Summary

This is a new pull request for turning in the Milestone 1 for review by the Directors. Thank you.

### Pull Request Checklist
- [x] Code is neat, readable, and works
- [x] Comments are appropriate
- [x] The commit message follows our guidelines
- [x] The milestone number is specified
- [x] The developer name is specified
- [x] The summary is completed

### Reviewer Checklist  - PULL REQUEST REVIEWER ONLY

IMPORTANT: The rest of the sections in this checklist should only be filled out by authorized pull request reviewers. If you are the individual template contributor, do not fill out the rest of the fields or check the boxes.

NOTE: Milestones can only be completed when all boxes are checked.

- [x] The code is fully reviewed
- [x] Meaningful feedback is given
- [x] Comment that you have reviewed the code
- [x] This box is checked

### CODE REVIEW

**Review by khoa-l — CHANGES_REQUESTED** [review]
Your website is really well put together and I like the styling! Your code is also well organized, great job! Do remember to commit as you code and not in one big one thought. Please move your code to the `main` branch and make a pull request from there to be marked complete!

That aside, great work on Milestone!!

**Comment by sylochloe** [comment]
Should I checkout all the boxes before I merge the change or wait for reviewer to do it?

**Comment by khoa-l** [comment]
> Should I checkout all the boxes before I merge the change or wait for reviewer to do it?

I'm not quite sure what this means? You shouldn't have to merge any changes, unless you mean from your milestone1 branch to main - in that case since it's your own branch you can feel free to check the boxes.

Once it's in main make a new pull request to this repository and we'll handle it from there!

**Comment by khoa-l** [comment]
Closing to allow merge into `main` from `milestone1`

**Pull request closed without merging**
