### PR TITLE
Milestone 1 - Joseph Hammana

### PR DESCRIPTION
**Pull request by Hammana963**
# Milestone: 1, 3, 3.5, 4 ,and 5
# Developer: Joseph Hammana

### Pull Request Summary

This is a pull request for turning in Milestone 1, 3, 3.5, 4, and 5.

### Pull Request Checklist
- [x] Code is neat, readable, and works
- [x] Comments are appropriate
- [x] The commit message follows our guidelines
- [x] The milestone number is specified
- [x] The developer name is specified
- [x] The summary is completed

### Reviewer Checklist  - PULL REQUEST REVIEWER ONLY

IMPORTANT: The rest of the sections in this checklist should only be filled out by authorized pull request reviewers. If you are the individual template contributor, do not fill out the rest of the fields or check the boxes.

NOTE: Milestones can only be completed when all boxes are checked.

- [x] The code is fully reviewed
- [x] Meaningful feedback is given
- [x] Comment that you have reviewed the code
- [x] This box is checked

### CODE REVIEW

**Review by vwinstea — CHANGES_REQUESTED** [review]
Please resubmit with your own CSS. Writing CSS is an essential part of web development, and not practicing this skill will substantially hamper your ability to contribute to your team.

**Comment by Hammana963** [comment]
I have recommitted with my own css, thanks.

**Comment by Hammana963** [comment]
Hello, I have pushed my completed code for Milestone 3 and added it to this request. Since my Milestone 1 has not been reviewed yet I changed the title and summary to reflect that. Please let me know if this works, thanks.

**Comment by Hammana963** [comment]
Completed Milestone 3.5

**Comment by Hammana963** [comment]
Completed and tested Milestone 4

**Comment by Hammana963** [comment]
Completed and tested Milestone 5!

**Comment by vwinstea** [comment]
Everything works great! Well done, you're officially done with bootcamp!

**Pull request closed without merging**
