### PR TITLE
Milestone 3, 3.5, 4, 5 - Adrian Nguyen

### PR DESCRIPTION
**Pull request by hnadrian**
# Milestone: 3, 3.5, 4, 5
# Developer: Adrian Nguyen

### Pull Request Summary

Submit a pull request for my Milestone 3, 3.5, 4 , 5project to be reviewed.

### Pull Request Checklist
- [x] Code is neat, readable, and works
- [x] Comments are appropriate
- [x] The commit message follows our guidelines
- [x] The milestone number is specified
- [x] The developer name is specified
- [x] The summary is completed

### Reviewer Checklist  - PULL REQUEST REVIEWER ONLY

IMPORTANT: The rest of the sections in this checklist should only be filled out by authorized pull request reviewers. If you are the individual template contributor, do not fill out the rest of the fields or check the boxes.

NOTE: Milestones can only be completed when all boxes are checked.

- [ ] The code is fully reviewed
- [ ] Meaningful feedback is given
- [ ] Comment that you have reviewed the code
- [ ] This box is checked

### CODE REVIEW

**Review by vwinstea — CHANGES_REQUESTED** [review]
Hey Adrian! Unfortunately your website is not working for me right now because it's giving me a CORS error on the backend. Luckily that fix is pretty easy and you can find it [here](https://h4i.notion.site/CORS-Errors-with-React-96046ac5b0e54fe2a144fcf3e56f6c7e). I tested this fix myself, and it worked, but you did have one other issue with your project because the add ingredient/ add instruction fields don't work. This is because your backend is expecting the body to look like {ingredient: "new ingredient"}, but the frontend is sending something that looks like this {newIngredient: "new Ingredient"}. Once you get those two fixes in you should be officially done with bootcamp, nice work so far!

**Comment by hnadrian** [comment]
@vwinstea 
Thanks for the suggestions! I have made these changes. However, I am having a fetch error when doing "npm start" on the project. It originates from `fetch("http://localhost:3001/recipe")` in my Home.tsx file.

**Comment by khoa-l** [comment]
> @vwinstea Thanks for the suggestions! I have made these changes. However, I am having a fetch error when doing "npm start" on the project. It originates from `fetch("http://localhost:3001/recipe")` in my Home.tsx file.

Would you be able to post a screenshot of the error?

**Comment by hnadrian** [comment]
Screen Shot 2022-12-22 at 11 44 24 PM
Here is a screenshot of the console

**Comment by vwinstea** [comment]
That's really weird because those changes you made are working for me now. Are you sure your backend was running at the same time as your frontend? The CORS error is fixed for me now, but the add ingredients/add instructions routes still don't work for me. The expected behavior is that if you add an ingredient and refresh the page the change persists. I think it doesn't work right now because some of your data is still locally sourced instead of coming from the database.

**Comment by hnadrian** [comment]
Hi, you are right I didn't run both the back and front ends correctly. I just removed a local data dependency I missed in the recipe page. It should all work now. Thank you so much!

**Comment by khoa-l** [comment]
This looks great! Especially love the little touches for hovering over the recipe cards! Also, great work on your commit messages and consistent history. Congratulations on completing your recipe project!

**Pull request closed without merging**
